/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ElD: typeof import('element-plus/es')['ElD']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
}
